---
title: Jess Darnes
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    is_page: true
    layout: page
- scope:
    path: ''
    type: posts
  values:
    is_post: true
    layout: post
    image: 
permalink: pretty
tagline: Copywriter, Illustrator & Designer
description: This is the website of Jess Darnes - Writer based in Bristol, UK
url: https://jessdarneswrites.com
author:
  name: Jess Darnes Writes
  url: https://twitter.com/jessdarnes
paginate: 5
version: 2.1.0
github:
  repo: https://github.com/jessdarneswrites/jessdarneswrites.github.io
excerpt_separator: "<!--more-->"
links:
  Instagram: https://instagram.com/jessdarneswrites/
  Pinterest: https://www.pinterest.com/jessdarneswrites/
  Twitter: http://twitter.com/jessdarnes
  Flickr: https://www.flickr.com/photos/ohtothejaydizzle
gems:
- jemoji
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
jekyll-mentions: https://twitter.com
meta:
  twitter: jessdarnes
sass:
  style: compressed
