---
title: Jess Gurr
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    is_page: true
    layout: page
- scope:
    path: ''
    type: posts
  values:
    is_post: true
    layout: post
permalink: pretty
tagline: Copywriter, Illustrator & Designer
description: This is the website of Jess Gurr - Copywriter, Illustrator and Designer
  based in Bristol, UK
url: http://jessgurr.com
author:
  name: Jess Gurr
  url: https://twitter.com/jessgurrwrites
paginate: 5
version: 2.1.0
github:
  repo: https://github.com/JessGurr/jessgurr.github.io
excerpt_separator: "<!--more-->"
links:
  Instagram: https://instagram.com/jessgurrwrites/
  Pinterest: https://www.pinterest.com/jessgurrwrites/
  Twitter: http://twitter.com/jessgurrwrites
  Flickr: https://www.flickr.com/photos/ohtothejaydizzle
gems:
- jemoji
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
jekyll-mentions: https://twitter.com
meta:
  twitter: jessgurrwrites
sass:
  style: compressed
