# Permalinks
permalink: pretty

# Setup
title: Jess Gurr
tagline: 'Copywriter, Illustrator & Designer'
description: 'This is the website of Jess Gurr - Copywriter, Illustrator and Designer based in Bristol, UK'
url: http://jessgurr.com

author:
  name: 'Jess Gurr'
  url: https://twitter.com/jessgurrwrites

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo: https://github.com/JessGurr/jessgurr.github.io

# Posts
excerpt_separator: <!--more-->

# Sidebar links
links:
  Instagram: "https://instagram.com/jessgurrwrites/"
  Pinterest: "https://www.pinterest.com/jessgurrwrites/"
  Twitter: "http://twitter.com/jessgurrwrites"
  # GitHub: "http://github.com/JessGurr"
  # Behance: "http://flickr.com/wildfire198"
  Flickr: "https://www.flickr.com/photos/ohtothejaydizzle"

# Gems
gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate

jekyll-mentions: https://twitter.com

# Meta
meta:
  twitter: jessgurrwrites

# SCSS
sass:
  style: :compressed

# Defaults
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      is_page: true
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true
      layout: post
