# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Jess Gurr
tagline:          'Copywriter, Illustrator & Designer'
description:      'This is the website of Jess Gurr - Copywriter, Illustrator and Designer based in Bristol, UK'
url:              http://jessgurr.com
baseurl:          

author:
  name:           'Jess Gurr'
  url:            https://twitter.com/JessicaGurr

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/JessGurr/jessgurr.github.io

# Posts
excerpt_separator: <!--more-->

# Sidebar links
links:
  Instagram: "https://instagram.com/jessgurrwrites/"
  Pinterest: "https://www.pinterest.com/jessgurrwrites/"
  Twitter: "http://twitter.com/JessicaGurr"
  # GitHub: "http://github.com/JessGurr"
  # Behance: "http://flickr.com/wildfire198"
  Flickr: "https://www.flickr.com/photos/ohtothejaydizzle"


# Gems
gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-mentions

jekyll-mentions: https://twitter.com

# Meta
meta:
  twitter: JessicaGurr
